config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/index'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :edit, :show, :create, :update, :destroy]#controller name
  resources :users, only: [:show, :index, :edit, :update]

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
      @books = Book.all
      @book = Book.new
      @user = current_user

  end

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
      else
        @books =Book.all
        #@book = Book.new
        @user = current_user
        render :index
      end
      #book = Book.new(book_params)
      #book.user_id = current_user.id#15
      #book.save
      #redirect_to book_path(book.id)
  end

  def show
      @book_show = Book.find(params[:id])
      @user_show = @book_show.user
      #@user = User.find(params[:id])
      
      #@user_current = current_user#部分テンプレートでつかってる
     # @user = User.find(params[:id])
      @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == @book.user_id
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book.id)
   else
      render :edit
   end
  end

  def destroy
    book = Book.find(params[:id])
    book.user_id = current_user.id
    book.destroy
    redirect_to books_path
  end

private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <div>
      <%= attachment_image_tag user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg" %>
  </div>
   <table class="table" >
       <tbody>
         <tr>
            <th>name</th>
            <th><%= user.name %></th>
         </tr>
         <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
         </tr>
       </tbody>
   </table>
  <div>
        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block btn-sm mt-4" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
  </div>
  <h2>New book</h2>

<%= form_with model:book, url: books_path, method: :post, local:true do |f| %>
  <div class="from-group">
    <label><%= f.label :title %></label>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="from-group">
    <label><%= f.label :opinion %></label>
  <%= f.text_area :body, class: "form-control book_title" %>
  </div>
  <div class="from-group">
  <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
</div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>

      <div class="error_messages">
       <% if @book.errors.any? %>
         <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
          <lu><% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
              <% end %>
          </lu>
       <% end %>
      </div>
<div>
<%= form_with model:@book, local:true do |f| %>
  <div class="form-group">
    <label for="inputName">Title</label><br>
    <%= f.text_field :title, class: "form-control book_title" %><br>
  </div>
  <div class="form-group">
    <label for="inputText">Opinion</label><br>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Book", class: "btn btn-success" %>
  </div>
<% end %>
</div>
<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="error_messages">
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  <lu><% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
  </lu>
  <% end %>
  </div>
 <div class="row">
   <%= render 'books/list', book: @book, user: @user %>
   <div class="col-md-8 offset-md-1">
     <h2>Books</h2>

       <table class="table table-hover table-inverse">
         <thead>
           <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
             <th colspan="3"></th>
           </tr>
         </thead>
         <tbody>
           <% @books.each do |book| %>
             <tr>
               <%= link_to user_path(book.id) do %>
               <td><%= attachment_image_tag book.user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg", size:'50x50' %></td>
               <% end %>
               <td><%= link_to book.title, book_path(book.id) %></td> <!--blogモデル内のtitleカラムという意味-->
               <td><%= book.body %></td>
             </tr>
           <% end %>
         </tbody>
       </table>
   </div>
 </div>
 </div>
<!--ここから共通-->

app/views/books/show.html.erb
<div class="container">
  <p class="success_massege"><%= flash[:notice] %></p>
  <div class="row">

      <%= render 'books/list', book: @book, user: @user_show %>
        <div class="col-md-8 offset-md-1">

          <h2>Book detail</h2>
            <table class="table">
              <tbody>
                <tr>
                  <td>
                    <%= link_to user_path(@user_show.id) do %>
                    <%= attachment_image_tag @user_show, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: '40x40' %><br>
                    <% end %>
                    <%= link_to @user_show.name, user_path(@user_show.id) %>
                  </td>
                  <td><%= link_to @book_show.title, book_path(@book_show.id) %></td>
                  <td><%= @book_show.body %></td>
                  <% if @book_show.user_id == current_user.id %>
                    <td><%= link_to "Edit",edit_book_path(params[:id]), class: "btn btn-sm btn-success" %></td>
                    <td><%= link_to "Destroy",book_path(params[:id]), method: :delete, class: "btn btn-danger btn-sm", "data-confirm" => "本当に消しますか？"  %></td>
                  <% end %>
                </tr>
             </tbody>
           </table>
        </div>
  </div>
</div>