config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/index'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :edit, :show, :create, :update, :destroy]#controller name
  resources :users, only: [:show, :index, :edit, :update]

end

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: #{key}) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/69c12d45f9.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
     <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="container">
           <a class="navbar-brand" href="/">
             <span>Bookers</span>
           </a>
           <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav ml-auto">
               <% if user_signed_in? %>
                 <li><%= link_to"Home", user_path(current_user.id), class: "fas fa-home nav-link text_light" %></li>
                 <li><%= link_to"Users", users_path, class: "fas fa-users nav-link text_light" %></li>
                 <li><%= link_to"Books", books_path, class: "fas fa-book-open nav-link text_light" %></li>
                 <li><%= link_to"Log out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text_light" %></li>
               <% else %>
                 <li> <%= link_to"Home", root_path, class: "fas fa-home nav-link text_light" %></li>
                 <li> <%= link_to"About", home_about_path, class: "fas fa-link nav-link text_light" %></li>
                 <li><%= link_to"Sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text_light" %></li>
                 <li><%= link_to"Log in", new_user_session_path, class: "fas fa-sign-in-alt nav-link text_light" %></li>
              <% end %>
             </ul>
           </div>
         </div>
       </nav>
     </header>
    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>